// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package mysqldb

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from db_wire.go:

func InitMySQL() error {
	mySQLConfig := ReadMySQLConfig()
	error2 := InitMySQLClient(mySQLConfig)
	return error2
}

func InitViper() error {
	error2 := NewViper()
	return error2
}
